import jwt from 'jsonwebtoken';
import * as Organization from '../models/Organization.js';
import * as User from '../models/User.js';
import * as LicenseConfig from '../models/LicenseConfig.js';
import {
  CLIENT_SERVICE_PULSE,
  organizationHasService,
} from '../services/clientServices.js';

function getSecret() {
  const s = process.env.JWT_SECRET;
  if (!s) throw new Error('JWT_SECRET is required');
  return s;
}

function jwtOptions() {
  const opts = { algorithms: ['HS256'] };
  if (process.env.JWT_ISSUER) opts.issuer = process.env.JWT_ISSUER;
  if (process.env.JWT_AUDIENCE) opts.audience = process.env.JWT_AUDIENCE;
  return opts;
}

export function signToken(payload, { expiresIn } = {}) {
  return jwt.sign(payload, getSecret(), {
    algorithm: 'HS256',
    expiresIn: expiresIn || process.env.JWT_EXPIRES_IN || '7d',
    issuer: process.env.JWT_ISSUER || undefined,
    audience: process.env.JWT_AUDIENCE || undefined,
  });
}

export function requireAuth(req, res, next) {
  const header = req.headers.authorization;
  const token = header?.startsWith('Bearer ') ? header.slice(7) : null;
  if (!token) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  let decoded;
  try {
    decoded = jwt.verify(token, getSecret(), jwtOptions());
  } catch {
    return res.status(401).json({ error: 'Invalid token' });
  }
  (async () => {
    try {
      const active = await User.isUserActive(decoded.sub);
      if (!active) {
        return res.status(401).json({ error: 'Account is no longer active' });
      }
      req.user = {
        id: decoded.sub,
        role: decoded.role,
        organizationId: decoded.organizationId,
        organizationKind: decoded.organizationKind,
        mfaVerifiedAt: decoded.mfaVerifiedAt || null,
        // SUP-01: when the token was minted via the impersonation flow,
        // these fields carry the platform admin's identity for audit
        // logging and tell blockSupportWrites to refuse mutations.
        supportImpersonation: Boolean(decoded.supportImpersonation),
        supportActorUserId: decoded.supportActorUserId || null,
        supportTargetOrgId: decoded.supportTargetOrgId || null,
      };
      next();
    } catch (e) {
      next(e);
    }
  })();
}

const SAFE_METHODS = new Set(['GET', 'HEAD', 'OPTIONS']);

/**
 * SUP-01 write guard. Mount BEFORE any router that has mutation routes.
 * If the current token was minted via the support-impersonation flow,
 * any non-safe HTTP method is refused with 403 — no audit trail is
 * generated by the blocked attempt itself (we already audited the
 * impersonation start), but a single line is logged so we can
 * investigate "why did support hit a write?" from logs alone.
 */
export function blockSupportWrites(req, res, next) {
  if (!req.user?.supportImpersonation) return next();
  if (SAFE_METHODS.has(req.method)) return next();
  console.warn('SUP-01 blocked write during impersonation', {
    actor: req.user.supportActorUserId,
    targetOrg: req.user.supportTargetOrgId,
    method: req.method,
    path: req.originalUrl,
  });
  return res.status(403).json({ error: 'Read-only support session: writes are disabled' });
}

export function requireAdmin(req, res, next) {
  if (req.user?.role !== 'admin') {
    return res.status(403).json({ error: 'Admin only' });
  }
  const enforceAdminMfa = String(process.env.MFA_ENFORCE_ADMIN || 'true').trim().toLowerCase() !== 'false';
  if (enforceAdminMfa && !req.user?.mfaVerifiedAt) {
    return res.status(403).json({ error: 'MFA required for admin actions' });
  }
  next();
}

export async function requireClientOrganization(req, res, next) {
  try {
    const org = req.clientOrganization || (await Organization.getOrganization(req.user.organizationId));
    if (!org || org.kind !== 'client') {
      return res.status(403).json({ error: 'Client organization only' });
    }
    req.clientOrganization = org;
    next();
  } catch (e) {
    next(e);
  }
}

export async function requirePlatformAdmin(req, res, next) {
  try {
    const org = await Organization.getOrganization(req.user.organizationId);
    if (!org || org.kind !== 'platform') {
      return res.status(403).json({ error: 'Platform only' });
    }
    if (req.user?.role !== 'admin') {
      return res.status(403).json({ error: 'Admin only' });
    }
    req.platformOrganization = org;
    next();
  } catch (e) {
    next(e);
  }
}

export async function requirePlatformUser(req, res, next) {
  try {
    const org = await Organization.getOrganization(req.user.organizationId);
    if (!org || org.kind !== 'platform') {
      return res.status(403).json({ error: 'Platform only' });
    }
    req.platformOrganization = org;
    next();
  } catch (e) {
    next(e);
  }
}

// A workspace user is anyone who can run a platform-style CRM workspace:
// either Outlier platform staff or a licensee admin/employee. Both share the
// same /platform/* API surface but with different scoping rules applied per
// route (see scopeable helpers in routes/platform/shared.js).
export async function requireWorkspaceUser(req, res, next) {
  try {
    const org = await Organization.getOrganization(req.user.organizationId);
    if (!org || (org.kind !== 'platform' && org.kind !== 'licensee')) {
      return res.status(403).json({ error: 'Workspace access required' });
    }
    if (org.kind === 'licensee') {
      const config = await LicenseConfig.getForOrganization(org.id);
      // SUP-01: support impersonation can read a suspended/expired
      // licensee's workspace — that's literally why the feature exists.
      // Writes are still blocked by blockSupportWrites.
      if (!req.user?.supportImpersonation && config && !LicenseConfig.isLicenseActive(config)) {
        const reason =
          config.status === 'expired'
            ? 'Your Rhythm Engine licence has expired. Contact Outlier to renew.'
            : config.status === 'suspended'
              ? 'Your Rhythm Engine licence has been suspended. Contact Outlier for support.'
              : 'Your Rhythm Engine licence is not active.';
        return res.status(402).json({ error: reason, licenceStatus: config.status });
      }
      req.licenseeLicenseConfig = config || null;
    }
    req.workspaceOrganization = org;
    if (org.kind === 'platform') req.platformOrganization = org;
    else req.licenseeOrganization = org;
    next();
  } catch (e) {
    next(e);
  }
}

/**
 * Lightweight admin-role gate for routes that already have workspace/org
 * scoping upstream. Call AFTER requireAuth (and usually after
 * requireWorkspaceUser / requirePlatformOnlyUser) — this only checks
 * `role === 'admin'`. Use requirePlatformAdmin if you need to assert
 * "platform org + admin role + MFA" in one go.
 */
export function requirePlatformAdminRole(req, res, next) {
  if (req.user?.role !== 'admin') {
    return res.status(403).json({ error: 'Admin only' });
  }
  next();
}

// Block routes that should only ever be reachable by Outlier platform staff
// (e.g. tasks, platform-wide service catalog, super-admin tooling).
export function requirePlatformOnlyUser(req, res, next) {
  const kind = req.workspaceOrganization?.kind;
  if (kind && kind !== 'platform') {
    return res.status(403).json({ error: 'Not available to licensees' });
  }
  if (kind) return next();
  // If requireWorkspaceUser was not run upstream, fall back to a defensive lookup.
  return Organization.getOrganization(req.user?.organizationId).then((org) => {
    if (!org || org.kind !== 'platform') {
      return res.status(403).json({ error: 'Not available to licensees' });
    }
    req.workspaceOrganization = org;
    req.platformOrganization = org;
    return next();
  }).catch(next);
}

export function buildRequireClientPulseService({
  getOrganization = Organization.getOrganization,
} = {}) {
  return async function requireClientPulseService(req, res, next) {
    try {
      const org = req.clientOrganization || (await getOrganization(req.user.organizationId));
      if (!org || org.kind !== 'client') {
        return res.status(403).json({ error: 'Client organization only' });
      }
      req.clientOrganization = org;
      if (!organizationHasService(org.settings, CLIENT_SERVICE_PULSE)) {
        return res.status(403).json({ error: 'Rhythm Engine is not enabled for this client' });
      }
      next();
    } catch (e) {
      next(e);
    }
  };
}

export const requireClientPulseService = buildRequireClientPulseService();
